# Generated by Django 5.0.6 on 2024-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
