# Generated by Django 5.0.6 on 2024-07-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventApp', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
