# Generated by Django 5.0.6 on 2024-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventApp', '0006_remove_order_items_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
